import React from 'react'
import Modal from '@/components/ui/Modal'
import { Button } from '@/components/ui/Button'

type Props = { open: boolean, onOpenChange: (v:boolean)=>void, payslip: any }

function buildPayslipHtml(payslip: any){
  const direction = document.documentElement.getAttribute('dir') || 'ltr'
  const vazir = "https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v30.1.0/dist/font-face.css"
  const company = payslip.company || { name: 'BizGenius', address: '' }

  const rows = `
    <table style="width:100%; border-collapse:collapse;">
      <thead>
        <tr>
          <th style="text-align:left; padding:8px; border-bottom:1px solid #e5e7eb">Item</th>
          <th style="text-align:right; padding:8px; border-bottom:1px solid #e5e7eb">Amount</th>
        </tr>
      </thead>
      <tbody>
        <tr><td style="padding:8px; border-bottom:1px solid #f3f4f6">Gross</td><td style="padding:8px; border-bottom:1px solid #f3f4f6; text-align:right">${payslip.gross}</td></tr>
        <tr><td style="padding:8px; border-bottom:1px solid #f3f4f6">Tax</td><td style="padding:8px; border-bottom:1px solid #f3f4f6; text-align:right">${payslip.tax}</td></tr>
        <tr><td style="padding:8px; font-weight:600">Net</td><td style="padding:8px; font-weight:600; text-align:right">${payslip.net}</td></tr>
      </tbody>
    </table>`

  const details = payslip.details ? payslip.details.map((d:any)=>`<div style="display:flex;justify-content:space-between;padding:6px 0"><div>${d.label}</div><div style="text-align:right">${d.value}</div></div>`).join('') : ''

  return `<!doctype html>
  <html lang="en" dir="${direction}">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>Payslip - ${payslip.name}</title>
      <link rel="stylesheet" href="${vazir}">
      <style>
        body { font-family: 'IRANSans', 'Vazir', system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial; color: #0f172a; padding: 20px }
        .card { max-width:800px; margin:0 auto; border:1px solid #e5e7eb; border-radius:8px; padding:20px }
        .header { display:flex; justify-content:space-between; align-items:center; margin-bottom:12px }
        .company { font-weight:700; font-size:18px }
        .meta { color:#6b7280; font-size:13px }
        .section { margin-top:12px }
        @media print { body { padding:0 } .card { border:none; box-shadow:none } }
      </style>
    </head>
    <body>
      <div class="card">
        <div class="header">
          <div>
            <div class="company">${company.name}</div>
            <div class="meta">${company.address || ''}</div>
          </div>
          <div style="text-align:right">
            <div style="font-weight:700">Payslip</div>
            <div class="meta">${payslip.period || ''}</div>
          </div>
        </div>

        <div class="section">
          <div style="display:flex;justify-content:space-between;align-items:center">
            <div>
              <div style="font-weight:600">Employee</div>
              <div class="meta">${payslip.name} &lt;${payslip.email || ''}&gt;</div>
              <div class="meta">${payslip.position || ''}</div>
            </div>
            <div style="text-align:right">
              <div style="font-weight:600">Payslip No</div>
              <div class="meta">${payslip.id || ''}</div>
              <div class="meta">Date: ${payslip.date || ''}</div>
            </div>
          </div>
        </div>

        <div class="section">
          ${rows}
        </div>

        <div class="section" style="margin-top:18px">
          ${details}
        </div>

        <div style="display:flex;justify-content:flex-end;margin-top:18px">
          <div style="text-align:right; color:#6b7280; font-size:12px">Generated by BizGenius</div>
        </div>
      </div>
    </body>
  </html>`
}

export default function PayslipModal({ open, onOpenChange, payslip }: Props){
  if (!payslip) return null

  const openPrintable = () => {
    const html = buildPayslipHtml(payslip)
    const w = window.open('', '_blank')
    if (!w) return
    w.document.write(html)
    w.document.close()
    // Give browser a moment to load fonts/styles then print
    setTimeout(()=> w.print(), 300)
  }

  const downloadPdf = () => {
    // Best-effort: open printable window and invoke print dialog (user can select Save as PDF)
    openPrintable()
  }

  return (
    <Modal open={open} onOpenChange={onOpenChange} title={`Payslip - ${payslip.name}`}>
      <div className="space-y-4">
        <div className="grid grid-cols-1 gap-2">
          <div className="flex justify-between">
            <div>
              <div className="font-semibold">{payslip.name}</div>
              <div className="text-sm text-muted-foreground">{payslip.email}</div>
              <div className="text-sm text-muted-foreground">{payslip.position}</div>
            </div>
            <div className="text-right">
              <div className="font-semibold">Net: {payslip.net}</div>
              <div className="text-sm text-muted-foreground">Period: {payslip.period}</div>
            </div>
          </div>

          <div className="p-3 border rounded bg-card">
            <div className="grid grid-cols-3 gap-2">
              <div>Gross</div>
              <div className="col-span-2 text-right">{payslip.gross}</div>
              <div>Tax</div>
              <div className="col-span-2 text-right">{payslip.tax}</div>
              <div className="font-semibold">Net</div>
              <div className="col-span-2 text-right font-semibold">{payslip.net}</div>
            </div>
          </div>

          <div className="flex gap-2 justify-end">
            <Button variant="outline" onClick={()=> onOpenChange(false)}>Close</Button>
            <Button onClick={openPrintable}>Print / Save PDF</Button>
            <Button variant="ghost" onClick={downloadPdf}>Download PDF</Button>
          </div>
        </div>
      </div>
    </Modal>
  )
}
